[[redirects]]
	from = "/faq-troubleshooting/other/the-app-is-saying-my-site-does-not-use-wordpress-even-though-it-does-how-to-fix"
	to = ""

[[redirects]]
	from = "/faq-troubleshooting/billing-refunds/should-i-upgrade-from-appsumo-to-developer-plan"
	to = ""

[[redirects]]
	from = "/changelog/app-changelog"
	to = ""

[[redirects]]
	from = "/faq-troubleshooting/other/auto-install-feature-for-the-plugin-is-not-working-properly"
	to = ""

[[redirects]]
	from = "/faq-troubleshooting/errors/error-the-url-url-is-invalid"
	to = ""

[[redirects]]
	from = "/faq-troubleshooting/other/does-the-patchstack-plugin-find-corrupted-files-or-malware"
	to = ""

[[redirects]]
	from = "/faq-troubleshooting/malware-cleanup/how-are-the-website-cleanups-made-in-patchstack"
	to = ""